<?php
/***************************************
 * http://www.program-o.com
 * PROGRAM O
 * Version: 2.6.11
 * FILE: allowedVars.php
 * AUTHOR: Elizabeth Perreau and Dave Morton
 * DATE: 01-19-2015
 * DETAILS: Contains an array of allowed form variables for the different admin pages,
 * along with the proper filters for each variable
 ***************************************/

$allowed_pages = [
    'botpersonality' => [
        'age'              => FILTER_DEFAULT,
        'baseballteam'     => FILTER_DEFAULT,
        'birthday'         => FILTER_DEFAULT,
        'birthplace'       => FILTER_DEFAULT,
        'botmaster'        => FILTER_DEFAULT,
        'boyfriend'        => FILTER_DEFAULT,
        'build'            => FILTER_DEFAULT,
        'celebrities'      => FILTER_DEFAULT,
        'celebrity'        => FILTER_DEFAULT,
        'class'            => FILTER_DEFAULT,
        'email'            => FILTER_DEFAULT,
        'emotions'         => FILTER_DEFAULT,
        'ethics'           => FILTER_DEFAULT,
        'etype'            => FILTER_DEFAULT,
        'family'           => FILTER_DEFAULT,
        'favoriteactor'    => FILTER_DEFAULT,
        'favoriteactress'  => FILTER_DEFAULT,
        'favoriteartist'   => FILTER_DEFAULT,
        'favoriteauthor'   => FILTER_DEFAULT,
        'favoriteband'     => FILTER_DEFAULT,
        'favoritebook'     => FILTER_DEFAULT,
        'favoritecolor'    => FILTER_DEFAULT,
        'favoritefood'     => FILTER_DEFAULT,
        'favoritemovie'    => FILTER_DEFAULT,
        'favoritemusician' => FILTER_DEFAULT,
        'favoritesong'     => FILTER_DEFAULT,
        'favoritesport'    => FILTER_DEFAULT,
        'feelings'         => FILTER_DEFAULT,
        'footballteam'     => FILTER_DEFAULT,
        'forfun'           => FILTER_DEFAULT,
        'friend'           => FILTER_DEFAULT,
        'friends'          => FILTER_DEFAULT,
        'gender'           => FILTER_DEFAULT,
        'genus'            => FILTER_DEFAULT,
        'girlfriend'       => FILTER_DEFAULT,
        'hockeyteam'       => FILTER_DEFAULT,
        'kindmusic'        => FILTER_DEFAULT,
        'kingdom'          => FILTER_DEFAULT,
        'language'         => FILTER_DEFAULT,
        'location'         => FILTER_DEFAULT,
        'looklike'         => FILTER_DEFAULT,
        'loves'            => FILTER_DEFAULT,
        'master'           => FILTER_DEFAULT,
        'name'             => FILTER_DEFAULT,
        'nationality'      => FILTER_DEFAULT,
        'order'            => FILTER_DEFAULT,
        'orientation'      => FILTER_DEFAULT,
        'party'            => FILTER_DEFAULT,
        'phylum'           => FILTER_DEFAULT,
        'president'        => FILTER_DEFAULT,
        'question'         => FILTER_DEFAULT,
        'religion'         => FILTER_DEFAULT,
        'sign'             => FILTER_DEFAULT,
        'size'             => FILTER_DEFAULT,
        'species'          => FILTER_DEFAULT,
        'talkabout'        => FILTER_DEFAULT,
        'version'          => FILTER_DEFAULT,
        'vocabulary'       => FILTER_DEFAULT,
        'wear'             => FILTER_DEFAULT,
        'website'          => FILTER_DEFAULT,
        'newEntryName'     => ['filter' => FILTER_DEFAULT, 'flags' => FILTER_REQUIRE_ARRAY],
        'newEntryValue'    => ['filter' => FILTER_DEFAULT, 'flags' => FILTER_REQUIRE_ARRAY],
        'bot_id'           => FILTER_SANITIZE_NUMBER_INT,
        'func'             => FILTER_DEFAULT,
        'action'           => FILTER_DEFAULT,
        'page'             => FILTER_DEFAULT,
    ],
    'clear' => [
        'action'    => FILTER_DEFAULT,
        'clearFile' => FILTER_DEFAULT,
        'page'      => FILTER_DEFAULT,
    ],
    'demochat' => [
        'page'      => FILTER_DEFAULT,
    ],
    'download' => [
        'type'      => FILTER_DEFAULT,
        'filenames' => FILTER_DEFAULT,
        'page'      => FILTER_DEFAULT,
    ],
    'editAiml' => [
        'page'    => FILTER_DEFAULT,
        'draw'    => FILTER_DEFAULT,
        'columns' => FILTER_DEFAULT,
        'order'   => FILTER_DEFAULT,
        'start'   => FILTER_DEFAULT,
        'length'  => FILTER_DEFAULT,
        'search'  => FILTER_DEFAULT,
        '_'       => FILTER_DEFAULT,
    ],
    'editAJAX' => [
        '_'           => FILTER_DEFAULT,
        'action'      => FILTER_DEFAULT,
        'columns'     => FILTER_DEFAULT,
        'draw'        => FILTER_DEFAULT,
        'filename'    => FILTER_DEFAULT,
        'id'          => FILTER_SANITIZE_NUMBER_INT,
        'length'      => FILTER_DEFAULT,
        'order'       => FILTER_DEFAULT,
        'pattern'     => FILTER_UNSAFE_RAW,
        'search'      => FILTER_DEFAULT,
        'start'       => FILTER_DEFAULT,
        'template'    => FILTER_UNSAFE_RAW,
        'thatpattern' => FILTER_UNSAFE_RAW,
        'topic'       => FILTER_UNSAFE_RAW,
    ],
    'editUDAiml' => [
        'page' => FILTER_DEFAULT,
    ],
    'logs' => [
        'showing' => FILTER_DEFAULT,
        'id'      => FILTER_DEFAULT,
        'page'    => FILTER_DEFAULT,
    ],
    'main' => [
        'page' => FILTER_DEFAULT,
    ],
    'members' => [
        'memberSelect'    => FILTER_DEFAULT,
        'user_name'       => FILTER_DEFAULT,
        'password'        => FILTER_DEFAULT,
        'passwordConfirm' => FILTER_DEFAULT,
        'id'              => FILTER_SANITIZE_NUMBER_INT,
        'action'          => FILTER_DEFAULT,
        'page'            => FILTER_DEFAULT,
    ],
    'select_bots' => [
        'bot_name'             => FILTER_DEFAULT,
        'bot_active'           => FILTER_DEFAULT,
        'format'               => FILTER_DEFAULT,
        'unknown_user'         => FILTER_DEFAULT,
        'debugemail'           => FILTER_DEFAULT,
        'default_aiml_pattern' => FILTER_DEFAULT,
        'error_response'       => FILTER_DEFAULT,
        'bot_desc'             => FILTER_DEFAULT,
        'bot_parent_id'        => FILTER_DEFAULT,
        'save_state'           => FILTER_DEFAULT,
        'remember_up_to'       => FILTER_DEFAULT,
        'conversation_lines'   => FILTER_DEFAULT,
        'debugmode'            => FILTER_DEFAULT,
        'debugshow'            => FILTER_DEFAULT,
        'bot_id'               => FILTER_SANITIZE_NUMBER_INT,
        'action'               => FILTER_DEFAULT,
        'useBranch'            => FILTER_DEFAULT,
        'page'                 => FILTER_DEFAULT,
    ],
    'spellcheck' => [
        'missspell'     => FILTER_DEFAULT,
        'correction'    => FILTER_DEFAULT,
        'group'         => FILTER_DEFAULT,
        'action'        => FILTER_DEFAULT,
        'page'          => FILTER_DEFAULT,
        'search'        => FILTER_DEFAULT,
        'missspelling'  => FILTER_DEFAULT,
        'id'            => FILTER_SANITIZE_NUMBER_INT,
    ],
    'srai_lookup' => [
        'page' => FILTER_DEFAULT,
    ],
    'teach' => [
        'topic'       => FILTER_DEFAULT,
        'thatpattern' => FILTER_DEFAULT,
        'pattern'     => FILTER_DEFAULT,
        'template'    => FILTER_DEFAULT,
        'action'      => FILTER_DEFAULT,
        'page'        => FILTER_DEFAULT,
    ],
    'upload' => [
        'clearDB' => FILTER_DEFAULT,
        'bot_id'  => FILTER_DEFAULT,
        'action'  => FILTER_DEFAULT,
        'page'    => FILTER_DEFAULT,
    ],
    'unknown_inputs' => [
        'id'   => FILTER_SANITIZE_NUMBER_INT,
        'page' => FILTER_DEFAULT,
    ],
    'wordcensor' => [
        'word_to_censor' => FILTER_DEFAULT,
        'replace_with'   => FILTER_DEFAULT,
        'censor_id'      => FILTER_DEFAULT,
        'group'          => FILTER_DEFAULT,
        'action'         => FILTER_DEFAULT,
        'page'           => FILTER_DEFAULT,
        'search'         => FILTER_DEFAULT,
    ],
    'login' => [
        'page'      => FILTER_DEFAULT,
        'user_name' => FILTER_DEFAULT,
        'pw'        => FILTER_DEFAULT,
    ],
    'logout' => [
        'page' => FILTER_DEFAULT,
    ],
    'stats' => [
        'page' => FILTER_DEFAULT,
    ],
    'bugs' => [
        'page'    => FILTER_DEFAULT,
        'name'    => FILTER_DEFAULT,
        'email'   => FILTER_DEFAULT,
        'subject' => FILTER_DEFAULT,
        'message' => FILTER_DEFAULT,
        'captcha' => FILTER_DEFAULT,
    ],
    'support' => [
        'page' => FILTER_DEFAULT,
    ],
    'search' => [
        'page' => FILTER_DEFAULT,
    ],
    'person' => [
        'page'   => FILTER_DEFAULT,
        'action' => FILTER_DEFAULT,
        'srch'   => FILTER_DEFAULT,
        'repl'   => FILTER_DEFAULT,
    ],
];
